# Generated by Django 4.2.3 on 2023-09-03 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAccesorio', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=240)),
                ('telefonoVendedor', models.IntegerField(max_length=12)),
                ('emailVendedor', models.EmailField(max_length=254)),
                ('imagenAccesorio', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCalzado', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=240)),
                ('telefonoVendedor', models.IntegerField(max_length=12)),
                ('emailVendedor', models.EmailField(max_length=254)),
                ('imagenCalzado', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='EventosBazaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('horario', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPrenda', models.CharField(max_length=15)),
                ('tela', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=240)),
                ('telefonoVendedor', models.IntegerField(max_length=12)),
                ('emailVendedor', models.EmailField(max_length=254)),
                ('imagenPrenda', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
