# Generated by Django 4.2.3 on 2023-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='telefonoVendedor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calzado',
            name='telefonoVendedor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='telefonoVendedor',
            field=models.IntegerField(),
        ),
    ]
